<?php
require '../lang/' . $language . '/include/months.inc';
$string['moreinformation'] = 'Więcej informacji';
$string['viewdetails'] = 'Ogląd szczegółów';
$string['debuginformation'] = 'Informacje dot. błędów';
$string['loadingdebug'] = 'Wyszukiwanie błędów ładowania';
$string['intermediateformatdebug'] = 'Wyszukiwanie błędów pośrednich';
$string['savingdebug'] = 'Zapisywanie wyników wyszukiwania błędów';
$string['generaldebuginfo'] = 'Ogólne informacje dot. błędów';
?>