<?php
require '../lang/' . $language . '/include/months.inc';
$string['moreinformation'] = 'More Information';
$string['viewdetails'] = 'View Details';
$string['debuginformation'] = 'Debug Information';
$string['loadingdebug'] = 'Loading Debug';
$string['intermediateformatdebug'] = 'Intermediate Format Debug';
$string['savingdebug'] = 'Saving Debug';
$string['generaldebuginfo'] = 'General Debug Info';
?>