<?php
$string['formative self-assessment'] = 'Formative Self-Assessment';
$string['progress test'] = 'Progress Test';
$string['summative exam'] = 'Summative Exam';
$string['survey'] = 'Survey';
$string['osce station'] = 'OSCE Station';
$string['offline paper'] = 'Offline Paper';
$string['formative self-assessments'] = 'Formative Self-Assessments';
$string['progress tests'] = 'Progress Tests';
$string['summative exams'] = 'Summative Exams';
$string['surveys'] = 'Surveys';
$string['osce stations'] = 'OSCE Stations';
$string['offline papers'] = 'Offline Papers';
?>