<?php
$string['passwordrequired'] = 'Password required';
$string['specificpassword'] = 'There is a specific password assigned to this paper.';
$string['enterpw'] = 'Please enter the password for this paper';
$string['pwcontinue'] = 'Continue';
$string['denied_location'] = 'Access to this paper is not permitted from your current location.';
$string['error_time'] = 'The paper you are attempting to access is only available between %s and %s';
$string['notregistered'] = '%s %s (%s) is not registered on <strong>%s</strong> in <strong>%s</strong>.';
$string['error_module'] = 'This paper is not on any module.';
$string['error_metadata'] = 'User metadata does not match <strong>%s: %s</strong>';
