<?php
$string['anytype'] = '(any type)';
$string['info'] = 'Information Block';
$string['keyword_based'] = 'Keyword-based Question';
$string['random'] = 'Random Question Block';
$string['calculation'] = 'Calculation';
$string['dichotomous'] = 'Dichotomous';
$string['extmatch'] = 'Extended Matching';
$string['blank'] = 'Fill-in-the-Blank';
$string['flash'] = 'Flash Interface';
$string['hotspot'] = 'Image Hotspot';
$string['labelling'] = 'Labelling';
$string['likert'] = 'Likert Scale';
$string['matrix'] = 'Matrix';
$string['mcq'] = 'Multiple Choice';
$string['mrq'] = 'Multiple Response';
$string['rank'] = 'Ranking';
$string['sct'] = 'Script Concordance Test';
$string['textbox'] = 'Text Box';
?>