<?php
$string['passwordrequired'] = 'Wymagane hasło'; 
$string['specificpassword'] = 'Do tego arkusza przypisane jest specyficzne hasło.';
$string['enterpw'] = 'Wprowadź hasło dla tego arkusza';
$string['pwcontinue'] = 'Dalej'; 
$string['denied_location'] = 'Dostęp do tego arkusza nie jest dozwolony z tej lokalizacji.';
$string['error_time'] = 'Arkusz, który chcesz zobaczyć dostępny jest tylko pomiędzy %s i %s';
$string['notregistered'] = '%s %s (%s) nie jest zarejestrowany na <strong>%s</strong> w <strong>%s</strong>.';
$string['error_module'] = 'Nie ma tego arkusza w żadnym module.';
$string['error_metadata'] = 'Metadane użytkownika nie są zgodne <strong>%s: %s</strong>';
