<?php
$string['error'] = 'Error';
$string['errormsg'] = 'If you repeatedly get this error please contact:';
$string['uploaderrormsg0'] = 'Error - ';
$string['uploaderrormsg1'] = 'No problem, the file is uploaded.';
$string['uploaderrormsg2'] = 'The uploaded file was bigger then  upload_max_filesize in php.ini.';
$string['uploaderrormsg3'] = 'The uploaded file was bigger then MAX_FILE_SIZE in html-form.';
$string['uploaderrormsg4'] = 'File partialy uploaded.';
$string['uploaderrormsg5'] = 'No file was uploaded.';
$string['uploaderrormsg6'] = 'No temp directory.';
$string['uploaderrormsg7'] = 'Unknown problem.';
$string['fatalerrormsg0'] = 'Fatal Error';
$string['fatalerrormsg1'] = 'A mandatory GET variable is missing.';
$string['fatalerrormsg2'] = 'A mandatory POST variable is missing.';
?>