<?php
$string['home'] = '1Home';
$string['help'] = '1Help';
$string['accessdenied'] = '1Access Denied';
$string['denied_paper'] = '1You are attempting to access a <strong>paper you do not have rights to</strong>!';
$string['denied_folder'] = '1You are attempting to access a <strong>folder you do not have rights to</strong>!';
$string['denied_question'] = '1You are attempting to access a <strong>question you do not have rights to</strong>!';
$string['denied_team'] = '1You are not a member of the <strong>%s</strong> module team.';
$string['noldapusernamesupplied'] = '1No LDAP username or password supplied';
$string['incorrectpassword'] = '1Incorrect password provided';
$string['ldapserverunavailable'] = '1LDAP Server Unavalable';
$string['noldapaccount'] = '1No LDAP account found!';
$string['ldapservernosearch'] = '1LDAP Server Unavalable: unable to search';
$string['nodatabaseconnection'] = '1Could not connect to the database please contact your administrator';
$string['localtsauthfailed'] = '1Local TouchStone authentication failed.';
$string['notsaccount'] = '1No TouchStone account found!';
$string['tempaccount'] = '1Temporary Account';
$string['authenticationfailed'] = '1Authentication with TouchStone has failed, please remember:';
$string['usernamecasesensitive'] = '1Usernames/passwords are case-sensitive';
$string['pressf5'] = "1Press 'F5' on the keyboard to try logging in again";
$string['tsonldap'] = '1TouchStone uses the LDAP passwords';
$string['ifstuckinvigilator'] = '1If you are still stuck ask an invigilator for a';
$string['forgottenpassword'] = '1Forgotten Password';
$string['warning'] = '1WARNING:';
$string['secureconnection'] = '1TouchStone can only be accessed through a secure web connection. Instead use:';
?>