<?php
$string['formative self-assessment'] = 'Formatywna samoocena';
$string['progress test'] = 'Test postępów';
$string['summative exam'] = 'Egzamin końcowy';
$string['survey'] = 'Ankieta';
$string['osce station'] = 'Stacja OSCE';
$string['offline paper'] = 'Arkusz Offline';
$string['formative self-assessments'] = 'Formatywne samooceny';
$string['progress tests'] = 'Testy postępów';
$string['summative exams'] = 'Egzaminy końcowe';
$string['surveys'] = 'Ankiety';
$string['osce stations'] = 'Stacje OSCE';
$string['offline papers'] = 'Arkusze Offline';
$string['peer review'] = 'Recenzja wewnętrzna';
$string['description0'] = 'Quizy dla samooceny, zwykle dostępne dla studentów w każdej chwili.';
$string['description1'] = 'Zwykle używane w testach śródsemestralnych, gdy wyniki nie są podawane na koniec sprawdzianu.';
$string['description2'] = "Egzaminy dużej wagi, których stopnie składają się na ocenę końcową studenta.";
$string['description3'] = 'Ankiety używane do poznania poglądów i pozyskania informacji od studentów.';
$string['description4'] = 'Sprawdziany OSCE (Objective Structured Clinical Examination) używane w medycynie.';
$string['description5'] = 'Ten typ arkusza umożliwia załadowanie do Rogo ocen z testów offline.';
$string['description6'] = 'Generuje formularz pozwalający studentom oceniać się wzajemnie.';
?>