<?php
$string['error'] = 'Błąd';
$string['errormsg'] = 'Jeśli ten błąd się powtarza skontaktuj się z:';
$string['uploaderrormsg0'] = 'Błąd - ';
$string['uploaderrormsg1'] = 'Brak błędów - plik załadowano.';
$string['uploaderrormsg2'] = 'Rozmiar ładowanego pliku jest większy niż przewidziany w upload_max_filesize w php.ini.';
$string['uploaderrormsg3'] = 'Rozmiar ładowanego pliku jest większy niż przewidziany w MAX_FILE_SIZE w html-form.';
$string['uploaderrormsg4'] = 'Plik częściowo załadowany.';
$string['uploaderrormsg5'] = 'Nie załadowano pliku.';
$string['uploaderrormsg6'] = 'Brak tymczasowego katalogu.';
$string['uploaderrormsg7'] = 'Nieznany problem.';
$string['fatalerrormsg0'] = 'Błąd krytyczny';
$string['fatalerrormsg1'] = 'Brak wymaganej zmiennej GET.';
$string['fatalerrormsg2'] = 'Brak wymaganej zmiennej POST.';
$string['fatalerrormsg3'] = 'Brak wymaganej zmiennej REQUEST.';
?>