<?php
require '../lang/' . $language . '/include/question_types.inc';
require '../lang/' . $language . '/include/paper_types.inc';

$string['papertasks'] = 'Działania dot. arkuszy';
$string['testpreview'] = 'Test i podgląd';
$string['addquestionspaper'] = 'Dodaj pytania do arkusza';
$string['editproperties'] = 'Edytuj właściwości';
$string['reports'] = 'Raporty';
$string['mappedobjectives'] = 'Cele odwzorowane';
$string['importmarks'] = 'Importuj punkty';//??
$string['standardssetting'] = 'Wyznaczanie standardu';
$string['importoscemarks'] = 'Importuj punkty OSCE';
$string['copypaper'] = 'Kopiuj arkusz';
$string['linktopaper'] = 'Powiąż z arkuszem';
$string['deletepaper'] = 'Usuń arkusz';
$string['retirepaper'] = 'Wycofaj arkusz';
$string['printhardcopy'] = 'Wydrukuj';
$string['qtiimportexport'] = 'Importowanie/ Eksportowanie QTI';
$string['export12'] = 'Eksport 1.2';
$string['import'] = 'Import';
$string['currentquestiontasks'] = 'Działania dot. aktualnego pytania';
$string['editquestion'] = 'Edytuj pytania';
$string['information'] = 'Informacja';
$string['copyontopaperx'] = 'Przekopiuj do arkusza X...';
$string['moveup'] = 'Przesuń do góry';
$string['movedown'] = 'Przesuń w dół';
$string['changescreenno'] = 'Zmień numer ekranu';
$string['removefrompaper'] = 'Usuń z arkusza';

$string['summativechecklist'] = 'Zestawienie końcowe';
$string['session'] = 'Sesja';
$string['mismatch'] = 'Niedopasowane';
$string['examtime'] = 'Czas egzaminu';
$string['incorrect'] = 'Nieprawidłowe';
$string['incomplete'] = 'Niekompletne';
$string['duration'] = 'Czas trwania';
$string['unset'] = 'Nieustalone';
$string['computerlabs'] = 'Pracownie komputerowe';
$string['peerreviewed'] = 'Zrecenzowano wewnętrznie';
$string['peerreviewes'] = 'Recenzje wewnętrzne';
$string['externalreviews'] = 'Recenzje zewnętrzne';
$string['standardsset'] = 'Standard wyznaczony';
$string['mapping'] = 'Odwzorowanie';

$string['questionbanktasks'] = 'Działania dot. banku pytań';
$string['questionsbytype'] = 'Pytania wg. typu';
$string['questionsbyteam'] = 'Pytania wg. zespołu';
$string['questionsbykeyword'] = 'Pytania wg. słowa kluczowego';
$string['search'] = 'Szukaj';
$string['createnewquestion'] = 'Utwórz nowe pytanie';

$string['questions'] = 'Pytania';
$string['papers'] = 'Arkusze';
$string['people'] = 'Osoby';
$string['studentcohort'] = 'Grupa studentów';  // Student Cohort of Paper

$string['startdate'] = 'Data rozpoczęcia';
$string['enddate'] = 'Data zakończenia';
$string['course'] = 'Kurs';
$string['anycourse'] = '&lt;Każdy kurs&gt;';
$string['module'] = 'Moduł';
$string['anymodule'] = '&lt;Każdy moduł&gt;';
$string['cohort'] = 'Grupa';
$string['allcandidates'] = 'Wszyscy kandydaci';//??
$string['top'] = 'Górna grupa';
$string['bottom'] = 'Dolna grupa';
$string['year'] = 'Rok';
$string['reviews'] = 'Recenzje';
$string['internalpeerreview'] = 'Recenzja wewnętrzna';
$string['externalexaminers'] = 'Zewnętrzni egzaminatorzy';
$string['sctresponses'] = 'Reakcje/Przyczyny SCT';
$string['classtotals'] = 'Całkowita liczba klas';//??
$string['classtotalsexcel2003'] = 'Całkowita liczba klas (Excel 2003)';
$string['classtotalscsv'] = 'Całkowita liczba klas (CSV file)';
$string['textboxmarking'] = 'Punktacja podręczników';//??
$string['primarymarkbyquestion'] = 'Początkowa punktacja pytań';
$string['selectpapersforremarking'] = 'Wybierz arkusze do wyróżnienia';//??
$string['secondmarkbyquestion'] = 'Wtórna punktacja pytań';//??
$string['finalisemarks'] = 'Zakończ punktację';
$string['frequencyanalysis'] = 'Analiza częstości i różnicowania (U-L)';
$string['learningobjectiveanalysis'] = 'Analiza celów kształcenia';
$string['exportresponsescsv'] = 'Eksportuj odpowiedzi jako plik CSV';
$string['exportmarkscsv'] = 'Eksportuj punktację jako plik CSV';
$string['individualportfoliosheets'] = 'Indywidualne arkusze Portfolio';
$string['exportratingscsv'] = 'Eksportuj zaszeregowanie jako plik CSV';
$string['xhtml'] = 'XHTML';
$string['word2003format'] = 'format Word 2003';
$string['rawdataxml'] = 'Czyste dane jako plik XML';
$string['rawdatacsv'] = 'Czyste dane jako plik CSV';
$string['itemanalysis'] = 'Analiza elementów';
$string['cohortreports'] = 'Raporty dot. grup';
$string['exports'] = 'Eksportowanie';
$string['quantitativereports'] = 'Raporty ilościowe';
$string['qualitativeanalysis'] = 'Analiza jakościowa';
$string['incabsentcandidates'] = 'uwzgl. kandydatów nieobecnych';
$string['completedatasets'] = 'Pokaż tylko pełne zbiory danych';

$string['copyname'] = 'Nazwa kopii:';
$string['paperonly'] = 'Tylko arkusze';
$string['paperandquestions'] = 'Arkusze i pytania';
$string['copypaper'] = 'Kopiuj arkusz';
$string['reorderinfo'] = 'Możesz teraz zmienić porządek pytań i przemieścić podzielniki ekranowe przeciągając je w nowe położenia';
$string['insertscreenbreak'] = 'Wprowadź podzielniki ekranowe';//Insert screen break';

?>