<?php
$string['formative self-assessment'] = 'Formatywna samoocena';
$string['progress test'] = 'Test postępów';
$string['summative exam'] = 'Egzamin końcowy';
$string['survey'] = 'Ankieta';
$string['osce station'] = 'Stacja OSCE';
$string['offline paper'] = 'Arkusz Offline';
$string['formative self-assessments'] = 'Formatywne samooceny';
$string['progress tests'] = 'Testy postępów';
$string['summative exams'] = 'Egzaminy końcowe';
$string['surveys'] = 'Ankiety';
$string['osce stations'] = 'Stacje OSCE';
$string['offline papers'] = 'Arkusze Offline';
?>