<?php
$string['anytype'] = '(każdy typ)';
$string['info'] = 'Blok informacji';
$string['keyword_based'] = 'Pytanie ze słowem kluczowym';
$string['random'] = 'Blok pytań losowych';
$string['calculation'] = 'Pytanie obliczeniowe';
$string['dichotomous'] = 'Pytanie rozróżniające';
$string['extmatch'] = 'Pytanie na dopasowanie';//rozbudowane pytanie na dopasowanie
$string['blank'] = 'Pytanie z luką';
$string['flash'] = 'Pytanie z interfejsem Flash';
$string['hotspot'] = 'Pytanie z miejscem aktywnym';//Hot spot
$string['labelling'] = 'Pytanie z etykietą graficzną';//
$string['likert'] = 'Skala Likerta';
$string['matrix'] = 'Macierz';
$string['mcq'] = 'Pytanie wielokrotnego wyboru';
$string['mrq'] = 'Pytanie wielu odpowiedzi';
$string['rank'] = 'Pytanie na stopniowanie';
$string['sct'] = 'Test scenariusza';//Test zgodności ze scenariuszem
$string['textbox'] = 'Pytanie półotwarte';
$string['true_false'] = 'Pytanie typu Prawda/Fałsz'; 
?>