<?php
require '../lang/' . $language . '/include/months.inc';
$string['moreinformation'] = 'More Information';
$string['viewdetails'] = 'View Details';
$string['debuginformation'] = 'Debug Information';
$string['loadingdebug'] = 'Loading Debug';
$string['intermediateformatdebug'] = 'Intermediate Format Debug';
$string['savingdebug'] = 'Saving Debug';
$string['generaldebuginfo'] = 'General Debug Info';
$string['addingtopaper'] = 'Adding to paper';
$string['params'] = 'Params';
$string['othherdebug'] = 'Other Debug';
$string['noquestions'] = 'No questions to load into Rogo';
$string['questiontables'] = 'Question Tables';
$string['questionsrow'] = 'questions row';
$string['optionsrows'] = 'options rows';
$string['newkeywords'] = 'new keywords';
$string['addingquestiondetails'] = 'adding question %d as display_pos = %d on screen %d';
