<?php
require '../lang/' . $language . '/include/months.inc';
$string['moreinformation'] = 'Więcej informacji';
$string['viewdetails'] = 'Ogląd szczegółów';
$string['debuginformation'] = 'Informacje dot. błędów';
$string['loadingdebug'] = 'Wyszukiwanie błędów ładowania';
$string['intermediateformatdebug'] = 'Wyszukiwanie błędów pośrednich';
$string['savingdebug'] = 'Zapisywanie wyników wyszukiwania błędów';
$string['generaldebuginfo'] = 'Ogólne informacje dot. błędów';

$string['addingtopaper'] = 'Dodawanie do arkusza';
$string['params'] = 'Parametry';
$string['othherdebug'] = 'Inne wyszukiwanie błędów';
$string['noquestions'] = 'Brak pytań do załadowania do Rogo';
$string['questiontables'] = 'Tablice pytań';
$string['questionsrow'] = 'wiersze pytań';
$string['optionsrows'] = 'wiersye opcji';
$string['newkeywords'] = 'Nowe słowa kluczowe';
$string['addingquestiondetails'] = 'dodawanie pytania %d jako display_pos = %d na ekranie %d';
