<?php
// This file is part of Rogō
//
// Rogō is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogō is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogō.  If not, see <http://www.gnu.org/licenses/>.

/**
* 
* @author Simon Wilkinson
* @version 1.0
* @copyright Copyright (c) 2012 The University of Nottingham
* @package
*/

?>
<div id="left-sidebar" class="sidebar">
<br />
<table cellpadding="0" cellspacing="0" border="0" width="185">
<tr><td style="font-weight:bold"><?php echo $string['administrativetools']; ?></td></tr>
<tr><td style="margin:4px">
<tr><td>
<table cellpadding="3" cellspacing="0" border="0" style="margin-left:6px; font-size:90%">
<tr><td><a href="../staff/index.php"><img src="../artwork/house.png" width="16" height="16" alt="<?php echo $string['home']; ?>" border="0" /></a></td><td class="menuitem"><a href="../staff/index.php"><?php echo $string['home']; ?></a></td></tr>
</table>

</td></tr>
</table>

</div>