<?php
$string['formative self-assessment'] = 'Formative Self-Assessment';
$string['progress test'] = 'Progress Test';
$string['summative exam'] = 'Summative Exam';
$string['survey'] = 'Survey';
$string['osce station'] = 'OSCE Station';
$string['offline paper'] = 'Offline Paper';
$string['formative self-assessments'] = 'Formative Self-Assessments';
$string['progress tests'] = 'Progress Tests';
$string['summative exams'] = 'Summative Exams';
$string['surveys'] = 'Surveys';
$string['osce stations'] = 'OSCE Stations';
$string['offline papers'] = 'Offline Papers';
$string['peer review'] = 'Peer Review';
$string['description0'] = 'Self-assessment quizzes that be normally be accessed by students at any time.';
$string['description1'] = 'Normally used for mid-term tests where feedback is not provided at the end of the assessment.';
$string['description2'] = "High-stakes exams where marks contribute to a student\'s course.";
$string['description3'] = 'A questionnaire used for eliciting views and feedback from students.';
$string['description4'] = 'Objective Structured Clinical Examination (OSCE) assessment type used for medical and health sciences fields.';
$string['description5'] = 'This paper type allows marks from offline papers to be loaded into Rogo.';
$string['description6'] = 'Generates a form for students to review their peers.';
?>